from enum import Enum


class BLSSuperSector(str, Enum):
    AGRICULTURE_FORESTRY_FISHING_HUNTING   = "AGRICULTURE_FORESTRY_FISHING_HUNTING",
    MINING_QUARRYING_OIL_GAS_EXTRACTION    = "MINING_QUARRYING_OIL_GAS_EXTRACTION",
    UTILITIES                              = "UTILITIES",
    CONSTRUCTION                           = "CONSTRUCTION",
    MANUFACTURING                          = "MANUFACTURING_TOTAL",
    WHOLESALE_TRADE                        = "WHOLESALE_TRADE",
    RETAIL_TRADE                           = "RETAIL_TRADE",
    TRANSPORTATION_WAREHOUSING             = "TRANSPORTATION_WAREHOUSING"
    INFORMATION                            = "INFORMATION"
    FINANCIAL_ACTIVITIES                   = "FINANCIAL_ACTIVITIES"
    REAL_ESTATE_RENTAL_LEASING             = "REAL_ESTATE_RENTAL_LEASING"
    PROFESSIONAL_BUSINESS_SERVICES         = "PROFESSIONAL_BUSINESS_SERVICES"
    MANAGEMENT_OF_COMPANIES                = "MANAGEMENT"
    ADMINISTRATIVE_WASTE_SERVICES          = "ADMINISTRATIVE_WASTE_SERVICES"
    EDUCATIONAL_SERVICES                   = "EDUCATIONAL_SERVICES"
    HEALTHCARE                             = "HEALTHCARE"
    LEISURE_HOSPITALITY                    = "LEISURE_HOSPITALITY"
    PUBLIC_ADMINISTRATION                  = "PUBLIC_ADMINISTRATION"
    OTHER_SERVICES_EXCEPT_PUBLIC_ADMIN     = "OTHER_SERVICES_EXCEPT_PUBLIC_ADMINISTRATION"
